title: Gabe Jauw  # You can add your name here

logo: logo.png # Use a relative path to logo image 

description: Student & Organizer // 'youth are the crops of our future!' 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: gabejauw@proton.me # Allow visitors to contact you
